version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'tintin'
      MYSQL_PASSWORD: 'choochoobus'
      MYSQL_ROOT_PASSWORD: 'new_password'
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql-data:

